---
apiVersion: v1
kind: Service
metadata:
  name: redis-ext-service
  labels:
    app: redis-cluster
spec:
  type: NodePort
  selector:
    app: redis-cluster
  ports:
  - name: redisport
    port: 6379
    targetPort: 6379
    nodePort: 30036
    protocol: TCP
